[package]
name = "meowos"
version = "0.1.0"
edition = "2024"

[workspace]
members = [ 
    "macros/traits",
    "macros/macros",
    "kernel",
    "kernel_test",
    "std"
]

[features]
run_tests = ["kernel/run_tests"]

[build-dependencies]
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none", features = [] }

[dependencies]
# used for UEFI booting in QEMU
ovmf-prebuilt = "0.1.0-alpha.1"

[profile.dev]
panic = "abort"
opt-level = 0
lto = false


[profile.release]
opt-level = 3          # regular speed optimizations
debug = false          # remove debug info
strip = "symbols"      # strip symbol table + debug symbols
lto = true             # link-time optimization
codegen-units = 1      # better optimization + dead code elimination
panic = "abort"        # no unwinding machinery
incremental = false    # smaller/final optimized build
overflow-checks = false

[profile.dev.package.std]
debug = true

[profile.release.package.std]
debug = true
