[package]
name = "kernel"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lints.rust]
dead_code = "allow"
static_mut_refs = "allow"

[lints.clippy]
needless_range_loop = "allow"
comparison_chain = "allow"
collapsible_else_if = "allow" #often it is not collapsed for conveying additional info
unwrap_used = "deny"
vec_init_then_push = "allow" #don't have vec! macro in no_std

[[bin]]
name = "kernel"
path = "src/main.rs"

[features]
run_tests = []

[dependencies]
kernel_test = { path = "../kernel_test"}
std = { path = "../std", features = ["test_includes"] }
macros = { path = "../macros/macros" }
traits = { path = "../macros/traits" }
bitfield = { git = "https://github.com/iKramp/rust-bitfield.git" } 
unroll = { path = "../unroll" }
uuid = {version = "1.16.0", default-features = false }
reg-map = { git = "https://github.com/iKramp/reg-map.git" }
static-cond = "0.3.0"
async-trait = "0.1.89"

[profile.release]
opt-level = 3          # regular speed optimizations
debug = false          # remove debug info
strip = "symbols"      # strip symbol table + debug symbols
lto = true             # link-time optimization
codegen-units = 1      # better optimization + dead code elimination
panic = "abort"        # no unwinding machinery
incremental = false    # smaller/final optimized build
overflow-checks = false
