[package]
name = "std"
version = "0.1.0"
edition = "2024"

[lints.rust]
dead_code = "allow"
static_mut_refs = "allow"

[lib]
crate-type = ["rlib"]

[dependencies]

[features]
test_includes = []

[profile.release]
opt-level = 3          # regular speed optimizations
debug = false          # remove debug info
strip = "symbols"      # strip symbol table + debug symbols
lto = true             # link-time optimization
codegen-units = 1      # better optimization + dead code elimination
panic = "abort"        # no unwinding machinery
incremental = false    # smaller/final optimized build
overflow-checks = false

